version: "3.9"
services: 
  mongo_database:
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
    image: mongo:${MONGO_VER}
    container_name: ${MONGO_NAME}
    working_dir: ${WORKDIR}
    volumes:
      - ${INTERNAL_STORAGE}:${EXTERNAL_STORAGE}
      - ${JS_CONFIG}:${WORKDIR}
    ports: 
      - ${PORT_SERV}:${PORT_CONT}
