version: "3.9"
services:

  verum_backend:
    env_file: ./.env_dev
    build: 
      context: ./
      dockerfile: Dockerfile-backend
    container_name: ${BACKEND_NAME}
    ports:
      - ${BACKEND_EXT_PORT}:${BACKEND_INT_PORT}
    
  verum_database:
    env_file: ./.env_dev
    environment:
      MONGO_INITDB_DATABASE: admin
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
    image: mongo:${MONGO_VER}
    container_name: ${DATABASE_NAME}
    working_dir: ${WORKDIR}
    volumes:
      - ./database/config/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
      - ${INTERNAL_STORAGE}:${EXTERNAL_STORAGE}
    ports:
      - ${MONGO_PORT}:27017
    

  verum_frontend:
    env_file: ./.env_dev
    build: 
      context: ./
      dockerfile: Dockerfile-frontend
    container_name: ${FRONTEND_NAME}
    ports: 
      - ${FRONTEND_EXT_PORT}:${FRONTEND_INT_PORT}
    