#!/usr/bin/zsh

#ESTABLECE VARIABLES DE ENTORNO
source .env

#CONSTRUYE EL DOCKERFILE
docker build . -t ${PYTHON_NAME}

#CREA Y PON EN OPERACION EL CONTROLADOR
docker run \
 -p ${PORT_SERV}:${PORT_CONT} \
 ${PYTHON_NAME} 
